LRU cache done
andSemin/oghw pull request #3
Opened 2023-05-25 14:54 UTC by andSemin

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-05-25 17:30 UTC, ityulkanov requested changes
В принципе код хороший, но я бы внёс пару правок. Отписал в комментариях

2023-05-25 23:50 UTC, andSemin commented on hw04_lru_cache/list.go
> +	l.len--
Добавил проверку

2023-05-25 23:50 UTC, andSemin commented on hw04_lru_cache/cache.go
> +	pointers map[*ListItem]Key
Долго думал, но фиксанул.

2023-05-25 23:58 UTC, andSemin commented on hw04_lru_cache/list.go
> +	if i != l.head {
Поправил

2023-05-26 07:21 UTC, ityulkanov commented on hw04_lru_cache/cache.go
>  }
```suggestion
	maps.Clear(c.items)
	c.queue = newList()
}
```

2023-05-26 07:21 UTC, ityulkanov approved these changes

2023-05-26 07:41 UTC, merged